-- DROP DATABASE IF EXISTS multidb;
-- DROP USER IF EXISTS multidbuser;

CREATE DATABASE multidb;

CREATE USER multidbuser WITH PASSWORD 'multidbpass';

GRANT ALL PRIVILEGES ON DATABASE multidb TO multidbuser;

\c multidb

GRANT USAGE, CREATE ON SCHEMA public TO multidbuser;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO multidbuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO multidbuser;
